[build]
  base = "."
  command = "cd frontend && npm install && npm run build && cd ../backend && pip install -r requirements.txt"
  publish = "frontend/dist"
  functions = "backend/netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.12.3"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[functions]
  external_node_modules = ["fastapi", "pandas", "numpy", "scikit-learn", "google-generativeai", "python-dotenv", "uvicorn", "pydantic", "requests"]
  node_bundler = "esbuild"