[build]
  base = "."
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[[redirects]]
  from = "/api/*"
  to = "https://tathmini-ai-backend.onrender.com/:splat"
  status = 200
  force = true